import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class ImageUserPicker extends StatefulWidget {
  ImageUserPicker({super.key, required this.pickimagefun});

  Function pickimagefun;
  @override
  State<ImageUserPicker> createState() => ImageUserPickerState();
}

class ImageUserPickerState extends State<ImageUserPicker> {
  @override
  Widget build(BuildContext context) {
    File? imageLoad;

    Future<void> takePicture() async {
      //the 'imageFile' is a path inside quatation with the image name generated by the camera
      final imageFile = await ImagePicker().pickImage(
        source: ImageSource.camera,
        maxWidth: 150,
        imageQuality: 50,
      );
      if (imageFile == null) {
        return;
      }
      setState(() {
        imageLoad = File(imageFile.path);
      });
      widget.pickimagefun(imageLoad);
    }

    return Column(
      children: [
        Container(
          decoration: BoxDecoration(
            border: Border.all(
              width: 2,
              color: Colors.grey,
            ),
            borderRadius: const BorderRadius.all(
              Radius.circular(9),
            ),
          ),
          alignment: Alignment.center,
          height: 150,
          width: 150,
          child: imageLoad != null
              ? Image.file(
                  imageLoad!,
                  fit: BoxFit.cover,
                  width: double.infinity,
                )
              : const Text(
                  'no image taken',
                  textAlign: TextAlign.center,
                ),
        ),
        TextButton.icon(
          onPressed: takePicture,
          icon: const Icon(Icons.image),
          label: const Text('addd image'),
        ),
      ],
    );
  }
}
